#
# dashboard config file
#
variables:
  - name: prometheus_api_server
    value: http://prometheus-server:9090
  - name: application_instance
    value: $APPLICATION_INSTANCE
  - name: sample_period
    value: 15m
  - name: timezone
    value: US/Pacific
dashboards:
    # application's display name
  - app_name: MyUW
    # status page url path: /{app_path}
    app_path: myuw
    # status page cache timeout (optional: default is 5 minutes)
    cache_timeout: 1
    application:
      # list of application components and the prometheus query to determine health
      - name: MyUW
        description: UW Campus Information Portal
        link: https://my.uw.edu
        # query should return boolean: "1" is healthy, "0" is not so much
        query: sum(some_metric{label1=value,label2=instance-$application_instance,label3=portion}[$sample_period]) / sum(some_metric{label1=value,label2=instance-$application_instance,label3=whole}[$sample_period])
        # metric result of the query greater than the threshold indicates health
        threshold: 0.99
        # value assigned on an empty metric result (default 0.0)
        on_null: 1.0
    dependencies:
      # list of each dependent service and the test to determine its healthiness
      - name: Student Web Service
        description: Service course and registration information
        query: sum(dependent_metric1{label1=value,label2=instance-$application_instance,label3=portion}[$sample_period]) / sum(dependent_metric1{label1=value,label2=instance-$application_instance,label3=whole}[$sample_period])
        threshold: 0.999
        on_null: 1.0
      - name: Person Web Service
        description: Service supplying person information
        query: sum(dependent_metric2{label1=value,label2=instance-$application_instance,label3=portion}[$sample_period]) / sum(dependent_metric2{label1=value,label2=instance-$application_instance,label3=whole}[$sample_period])
        threshold: 0.75
        on_null: 1.0
