#
# dashboard config file
#
variables:
  prometheus_api_server: http://prometheus-server:9090
  application_instance: $APPLICATION_INSTANCE
  sample_period: 15m
  timezone: US/Pacific
web-service-block: &web-service-block
    query: sum(dependent_metric1{label1=value,label2=${application}-${application_instance},label3=${service}}[${sample_period}]) / sum(dependent_metric1{label1=value,label2=${application}-${application_instance},label3=${service}}[${sample_period}])
    threshold:
      - limit: 0.999
        description: Some error responses
dashboards:
    # application's display name
  - app_name: MyUW
    # status page url path: /{app_path}
    app_path: myuw
    # url supplying dynamic status notification text
    #app_notification_url: https://some-server/some-path/myuw/some-file.html
    # status page cache timeout (optional: default is 5 minutes)
    cache_timeout: 1
    variables:
      application: myuw
    panels:
      - name: MyUW Status
        services:
          # dictionary of application components and the prometheus query to determine health
          - name: MyUW
            description: UW Campus Information Portal
            link: https://my.uw.edu
            # query should return boolean: "1" is healthy, "0" is not so much
            query: sum(some_metric{label1=value,label2=${application}-${application_instance},label3=portion}[${sample_period}]) / sum(some_metric{label1=value,label2=${application}-${application_instance},label3=whole}[${sample_period}])
            # metric results which produce error indicators listed in descending order
            threshold:
              - limit: 0.75
                description: Critical
              - limit: 0.99
                description: Degraded
      - name: Critical Services
        #description: Services required to provide MyUW access and content.
        critical_description: Some services show poor health.  MyUW is likely unavailable.
        services:
          # list of dependent services and the test to determine its healthiness
          - <<: *web-service-block
            name: Student Web Service
            #description: Service course and registration information
            critical_description: Course and registration information unavailble.  Login likely failing.
            variables:
               service: sws
          - <<: *web-service-block
            name: Person Web Service
            #description: Service supplying person information
            critical_description: Person information unavailable. MyUW login likely failing.
            variables:
               service: pws
      - name: Services Providing Content
        #description: Services providing specific MyUW content.
        critical_description: As not all services appear healthy, some MyUW content may be missing or displaying an error message.
        services:
          - <<: *web-service-block
            name: UWNetID Information
            #description: Service supplying campus service information
            critical_description: Some service information may be incomplete
            variables:
               service: uwnetid
          - <<: *web-service-block
            name: UW Canvas
            #description: Service supplying course information
            critical_description: Some course information may be incomplete
            variables:
               service: canvas
          - <<: *web-service-block
            name: UW Calendar
            #description: Service supplying event information
            critical_description: Event information may not be displayed
            link: https://www.washington.edu/calendar/
            variables:
               service: calendar
          - <<: *web-service-block
            name: Housing and Food Services
            #description: Husky card information
            critical_description: Husky card information may not be displayed
            variables:
               service: hfs
