autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

ingress:
  enabled: true
  type: nginx
  tls:
    dev-status-dashboard:
      secretName: status-test.dnatls.uw.edu-ingress-cert
      hosts:
        - status-test.dnatls.uw.edu
  hosts:
    dev-status-dashboard:
      host: status-test.dnatls.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/limit-rps: "10"

repo: status-dashboard
instance: test

containerPort: 8000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi

service:
  enabled: true
  ports:
    - port: 80
      targetPort: 8000
      name: http

deploymentInitialization:
  enabled: false

database:
  engine: null

metrics:
  enabled: true

readiness:
  enabled: true
  command:
    - "/scripts/ready.sh"


lifecycle:
  enabled: false

environmentVariables:
  - name: ENV
    value: dev
  - name: DASHBOARD_CONFIG_FILE
    value: /app/config/dashboard.yml

podVolumes:
  status-dashboard-config:
    volume:
      configMap:
        name: status-dashboard-config
    mount:
      mountPath: /app/config/dashboard.yml
      subPath: dashboard.yml
    containers: [ base ]

configmaps:
  status-dashboard-config:
    dashboard.yml: |
      variables:
        - name: prometheus_api_server
          value: http://prometheus-k8s.mci-monitoring.svc.cluster.local:9090
        - name: sample_period
          value: 10m
        - name: timezone
          value: US/Pacific
      dashboards:
          # application's display name
        - app_name: MyUW
          # status page url path: /{app_path}
          app_path: myuw
          # status page cache timeout (optional: default is 5 minutes)
          cache_timeout: 1
          application:
            # list of application components and the prometheus query to determine health
            - name: MyUW
              description: UW student and faculty information portal
              link: https://test.my.uw.edu
              #
              # query should return a scalar value to test the threshold values against
              #
              query: (sum(increase(nginx_ingress_controller_requests{exported_service="myuw-prod-test",controller_class=~"k8s.io/ingress-nginx",namespace=~"ingress-nginx",status=~"([123]..|40[134]|499|543)"}[$sample_period]) OR vector(1))) / (sum(increase(nginx_ingress_controller_requests{exported_service="myuw-prod-test",controller_class=~"k8s.io/ingress-nginx",namespace=~"ingress-nginx"}[$sample_period]) OR vector(1)))
              #
              # query results less than the threshold value indicates the service is struggling and displays the corresponding description
              #
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.99
                  description: Degraded
          dependencies:
            # A list of dependent services and the query to determine its healthiness
            - name: Groups Web Service (Blocker)
              description: Source of user affiliation data
              level: Blocker
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="gws", job="myuw-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="gws", job="myuw-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: UW Person Web Service (Blocker)
              description: Source of user person data
              level: Blocker
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="pws", job="myuw-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="pws", job="myuw-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: UW Student Web Service (Critical)
              description: Source of course, enrollment , notice, and registration data
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="sws", job="myuw-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="sws", job="myuw-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: Canvas API
              description: Source of Canvas course data
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="canvas", job="myuw-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="canvas", job="myuw-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: MyPlan Auth API
              description: Source of MyPlan authentocation
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="myplan_auth", job="myuw-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="myplan_auth", job="myuw-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: MyPlan API
              description: Source of MyPlan course data
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="myplan", job="myuw-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="myplan", job="myuw-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: UWNetID API
              description: Source of uwnetid password, subscription data
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="uwnetid", job="myuw-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="uwnetid", job="myuw-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: UW Library Account API
              description: Source of user library account information
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="libraries", job="myuw-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="libraries", job="myuw-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: Housing and Food Services API
              description: Provides Husky Card information
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="hfs", job="myuw-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="hfs", job="myuw-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: UW Bookstore API
              description: Source of course textbook data
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="book", job="myuw-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="book", job="myuw-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: Iasystem API
              description: Source of course evaluation data
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="iasystem", job="myuw-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="iasystem", job="myuw-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: UPASS API
              description: Source of UPASS data
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="upass", job="myuw-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="upass", job="myuw-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
        - app_name: Provision Request Tool
          # status page url path: /{app_path}
          app_path: provision
          # status page cache timeout (optional: default is 5 minutes)
          cache_timeout: 1
          application:
            # list of application components and the prometheus query to determine health
            - name: Provision Request Tool
              description: Service provisioning and lifecycle manager
              link: https://test.provision.uw.edu
              query: (sum(increase(nginx_ingress_controller_requests{exported_service="prt-prod-test",controller_class=~"k8s.io/ingress-nginx",namespace=~"ingress-nginx",status=~"([123]..|40[134]|499|543)"}[$sample_period]) OR vector(1))) / (sum(increase(nginx_ingress_controller_requests{exported_service="prt-prod-test",controller_class=~"k8s.io/ingress-nginx",namespace=~"ingress-nginx"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.99
                  description: Degraded
          dependencies:
            # list of each dependent service and the test to determine its healthiness
            - name: UW Person Web Service
              description: Source of personal information
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="pws", job="prt-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="pws", job="prt-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: Groups Web Service
              description: Provides UW institutional group information
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="gws", job="prt-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="gws", job="prt-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: UW NetID Web Service
              description: Source of personal information
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="uwnetid", job="prt-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="uwnetid", job="prt-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: MSCA Web Service
              description: UW Microsoft Collaborative Applications API
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="msca", job="prt-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="msca", job="prt-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
            - name: ITBill Web Service
              description: UW Billing Subscription Service API
              query: (sum(increase(restclient_response_status_code_bucket{exported_service="itbill", job="prt-prod-test", le=~"400(.0)?"}[$sample_period]) OR vector(1))) / (sum(increase(restclient_response_status_code_bucket{exported_service="itbill", job="prt-prod-test", le=~"500(.0)?"}[$sample_period]) OR vector(1)))
              threshold:
                - limit: 0.75
                  description: Critical
                - limit: 0.98
                  description: Degraded
